# Generated by Django 3.0.6 on 2021-02-04 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('times_taken', models.IntegerField(default=0, editable=False)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quizer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(default='', max_length=255)),
                ('option1', models.CharField(default=' ', max_length=255)),
                ('option2', models.CharField(default=' ', max_length=255)),
                ('option3', models.CharField(default=' ', max_length=255)),
                ('option4', models.CharField(default=' ', max_length=255)),
                ('correct_option', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('difficulty', models.IntegerField(choices=[(1, 'easy'), (2, 'medium'), (3, 'hard')], default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='quiz_api.Quiz')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('messages', models.CharField(default='', max_length=200)),
                ('username', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Quizer')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam', models.AutoField(primary_key=True, serialize=False)),
                ('section1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section1', to='quiz_api.Quiz')),
                ('section2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section2', to='quiz_api.Quiz')),
                ('section3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section3', to='quiz_api.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('question_attemted', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('date_finished', models.DateTimeField(auto_now_add=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Quizer')),
            ],
            options={
                'unique_together': {('user', 'quiz')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1', models.IntegerField(default=0)),
                ('level_2', models.IntegerField(default=0)),
                ('level_3', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Quizer')),
            ],
            options={
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
