# Generated by Django 3.0.6 on 2021-02-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0002_quizresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='user',
        ),
    ]
