# Generated by Django 3.0.6 on 2021-02-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0003_remove_quizresponse_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResponse',
        ),
    ]
