# Generated by Django 3.0.6 on 2021-02-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0004_delete_quizresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_1', models.CharField(default='', max_length=50)),
                ('score1', models.IntegerField()),
                ('quiz_2', models.CharField(default='', max_length=50)),
                ('score2', models.IntegerField()),
                ('quiz_3', models.CharField(default='', max_length=50)),
                ('score3', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_api.Quizer')),
            ],
        ),
    ]
