# Generated by Django 3.0.6 on 2021-02-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0005_totalresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
