# Generated by Django 3.0.6 on 2021-03-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0007_auto_20210302_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_two',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_image',
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
    ]
