# Generated by Django 3.0.6 on 2021-04-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0009_auto_20210304_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_four',
            field=models.ImageField(default='', upload_to='student/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_one',
            field=models.ImageField(default='', upload_to='student/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_three',
            field=models.ImageField(default='', upload_to='student/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_two',
            field=models.ImageField(default='', upload_to='student/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(default='', upload_to='student/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
