# Generated by Django 3.0.6 on 2021-04-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0010_auto_20210418_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image_two',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_image',
        ),
    ]
